[build]
  command = "npm run build"
  # Publish directory is handled by @netlify/plugin-nextjs
  # Setting to empty string to override UI setting
  # publish = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

